### ISSUE TITLE
Any hope for OpenID / OAuth support?

### ISSUE THREAD

**Issue by 411x** [ndom91/timeoff#20]
### Clear and concise description of the problem

Currently, the project only supports LDAP. Which is good, but not the best.

### Suggested solution

Auth management with openid or oauth ♥

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ndom91** [comment]
No sorry, this project is not being maintained at all anymore. You're free to fork or do with it what you please though 😊
